const ALLCURRENCIES = [
  {
    name: "United States Dollar",
    code: "USD",
    symbol: "$",
    country: "US",
  },
  {
    name: "United Arab Emirates Dirham",
    code: "AED",
    symbol: "د.إ",
    country: "AE",
  },
  {
    name: "Afghan Afghani",
    code: "AFN",
    symbol: "؋",
    country: "AF",
  },
  {
    name: "Albanian Lek",
    code: "ALL",
    symbol: "L",
    country: "AL",
  },
  {
    name: "Armenian Dram",
    code: "AMD",
    symbol: "֏",
    country: "AM",
  },
  {
    name: "Netherlands Antillean Guilder",
    code: "ANG",
    symbol: "ƒ",
    country: "CW, SX",
  },
  {
    name: "Angolan Kwanza",
    code: "AOA",
    symbol: "Kz",
    country: "AO",
  },
  {
    name: "Argentine Peso",
    code: "ARS",
    symbol: "$",
    country: "AR",
  },
  {
    name: "Australian Dollar",
    code: "AUD",
    symbol: "$",
    country: "AU",
  },
  {
    name: "Aruban Florin",
    code: "AWG",
    symbol: "ƒ",
    country: "AW",
  },
  {
    name: "Azerbaijani Manat",
    code: "AZN",
    symbol: "₼",
    country: "AZ",
  },
  {
    name: "Bosnia-Herzegovina Convertible Mark",
    code: "BAM",
    symbol: "KM",
    country: "BA",
  },
  {
    name: "Barbadian Dollar",
    code: "BBD",
    symbol: "$",
    country: "BB",
  },
  {
    name: "Bangladeshi Taka",
    code: "BDT",
    symbol: "৳",
    country: "BD",
  },
  {
    name: "Bulgarian Lev",
    code: "BGN",
    symbol: "лв",
    country: "BG",
  },
  {
    name: "Burundian Franc",
    code: "BIF",
    symbol: "FBu",
    country: "BI",
  },
  {
    name: "Bermudan Dollar",
    code: "BMD",
    symbol: "$",
    country: "BM",
  },
  {
    name: "Brunei Dollar",
    code: "BND",
    symbol: "$",
    country: "BN",
  },
  {
    name: "Bolivian Boliviano",
    code: "BOB",
    symbol: "Bs.",
    country: "BO",
  },
  {
    name: "Brazilian Real",
    code: "BRL",
    symbol: "R$",
    country: "BR",
  },
  {
    name: "Bahamian Dollar",
    code: "BSD",
    symbol: "$",
    country: "BS",
  },
  {
    name: "Botswanan Pula",
    code: "BWP",
    symbol: "P",
    country: "BW",
  },
  {
    name: "Belarusian Ruble",
    code: "BYN",
    symbol: "Br",
    country: "BY",
  },
  {
    name: "Belize Dollar",
    code: "BZD",
    symbol: "BZ$",
    country: "BZ",
  },
  {
    name: "Canadian Dollar",
    code: "CAD",
    symbol: "$",
    country: "CA",
  },
  {
    name: "Congolese Franc",
    code: "CDF",
    symbol: "FC",
    country: "CD",
  },
  {
    name: "Swiss Franc",
    code: "CHF",
    symbol: "CHF",
    country: "CH, LI",
  },
  {
    name: "Chilean Peso",
    code: "CLP",
    symbol: "$",
    country: "CL",
  },
  {
    name: "Chinese Yuan",
    code: "CNY",
    symbol: "¥",
    country: "CN",
  },
  {
    name: "Colombian Peso",
    code: "COP",
    symbol: "$",
    country: "CO",
  },
  {
    name: "Costa Rican Colón",
    code: "CRC",
    symbol: "₡",
    country: "CR",
  },
  {
    name: "Cape Verdean Escudo",
    code: "CVE",
    symbol: "$",
    country: "CV",
  },
  {
    name: "Czech Koruna",
    code: "CZK",
    symbol: "Kč",
    country: "CZ",
  },
  {
    name: "Djiboutian Franc",
    code: "DJF",
    symbol: "Fdj",
    country: "DJ",
  },
  {
    name: "Danish Krone",
    code: "DKK",
    symbol: "kr",
    country: "DK",
  },
  {
    name: "Dominican Peso",
    code: "DOP",
    symbol: "RD$",
    country: "DO",
  },
  {
    name: "Algerian Dinar",
    code: "DZD",
    symbol: "دج",
    country: "DZ",
  },
  {
    name: "Egyptian Pound",
    code: "EGP",
    symbol: "£",
    country: "EG",
  },
  {
    name: "Ethiopian Birr",
    code: "ETB",
    symbol: "ETB",
    country: "ET",
  },
  {
    name: "Euro",
    code: "EUR",
    symbol: "€",
    country: "AD",
  },
  {
    name: "Fijian Dollar",
    code: "FJD",
    symbol: "$",
    country: "FJ",
  },
  {
    name: "Falkland Islands Pound",
    code: "FKP",
    symbol: "£",
    country: "FK",
  },
  {
    name: "British Pound Sterling",
    code: "GBP",
    symbol: "£",
    country: "GB",
  },
  {
    name: "Georgian Lari",
    code: "GEL",
    symbol: "₾",
    country: "GE",
  },
  {
    name: "Gibraltar Pound",
    code: "GIP",
    symbol: "£",
    country: "GI",
  },
  {
    name: "Gambian Dalasi",
    code: "GMD",
    symbol: "D",
    country: "GM",
  },
  {
    name: "Guinean Franc",
    code: "GNF",
    symbol: "FG",
    country: "GN",
  },
  {
    name: "Guatemalan Quetzal",
    code: "GTQ",
    symbol: "Q",
    country: "GT",
  },
  {
    name: "Guyanese Dollar",
    code: "GYD",
    symbol: "$",
    country: "GY",
  },
  {
    name: "Hong Kong Dollar",
    code: "HKD",
    symbol: "HK$",
    country: "HK",
  },
  {
    name: "Honduran Lempira",
    code: "HNL",
    symbol: "L",
    country: "HN",
  },
  {
    name: "Haitian Gourde",
    code: "HTG",
    symbol: "G",
    country: "HT",
  },
  {
    name: "Hungarian Forint",
    code: "HUF",
    symbol: "Ft",
    country: "HU",
  },
  {
    name: "Indonesian Rupiah",
    code: "IDR",
    symbol: "Rp",
    country: "ID",
  },
  {
    name: "Israeli New Shekel",
    code: "ILS",
    symbol: "₪",
    country: "IL",
  },
  {
    name: "Indian Rupee",
    code: "INR",
    symbol: "₹",
    country: "IN",
  },
  {
    name: "Icelandic Króna",
    code: "ISK",
    symbol: "kr",
    country: "IS",
  },
  {
    name: "Jamaican Dollar",
    code: "JMD",
    symbol: "J$",
    country: "JM",
  },
  {
    name: "Japanese Yen",
    code: "JPY",
    symbol: "¥",
    country: "JP",
  },
  {
    name: "Kenyan Shilling",
    code: "KES",
    symbol: "Ksh",
    country: "KE",
  },
  {
    name: "Kyrgyzstani Som",
    code: "KGS",
    symbol: "с",
    country: "KG",
  },
  {
    name: "Cambodian Riel",
    code: "KHR",
    symbol: "៛",
    country: "KH",
  },
  {
    name: "Comorian Franc",
    code: "KMF",
    symbol: "CF",
    country: "KM",
  },
  {
    name: "South Korean Won",
    code: "KRW",
    symbol: "₩",
    country: "KR",
  },
  {
    name: "Cayman Islands Dollar",
    code: "KYD",
    symbol: "$",
    country: "KY",
  },
  {
    name: "Kazakhstani Tenge",
    code: "KZT",
    symbol: "₸",
    country: "KZ",
  },
  {
    name: "Lao Kip",
    code: "LAK",
    symbol: "₭",
    country: "LA",
  },
  {
    name: "Lebanese Pound",
    code: "LBP",
    symbol: "ل.ل",
    country: "LB",
  },
  {
    name: "Sri Lankan Rupee",
    code: "LKR",
    symbol: "₨",
    country: "LK",
  },
  {
    name: "Liberian Dollar",
    code: "LRD",
    symbol: "$",
    country: "LR",
  },
  {
    name: "Lesotho Loti",
    code: "LSL",
    symbol: "L",
    country: "LS",
  },
  {
    name: "Lithuanian Litas",
    code: "LTL",
    symbol: "Lt",
    country: "LT",
  },
  {
    name: "Latvian Lats",
    code: "LVL",
    symbol: "Ls",
    country: "LV",
  },
  {
    name: "Libyan Dinar",
    code: "LYD",
    symbol: "ل.د",
    country: "LY",
  },
  {
    name: "Moroccan Dirham",
    code: "MAD",
    symbol: "د.م.",
    country: "MA, EH",
  },
  {
    name: "Moldovan Leu",
    code: "MDL",
    symbol: "L",
    country: "MD",
  },
  {
    name: "Malagasy Ariary",
    code: "MGA",
    symbol: "Ar",
    country: "MG",
  },
  {
    name: "Macedonian Denar",
    code: "MKD",
    symbol: "ден",
    country: "MK",
  },
  {
    name: "Myanmar Kyat",
    code: "MMK",
    symbol: "K",
    country: "MM",
  },
  {
    name: "Mongolian Tugrik",
    code: "MNT",
    symbol: "₮",
    country: "MN",
  },
  {
    name: "Macanese Pataca",
    code: "MOP",
    symbol: "MOP$",
    country: "MO",
  },
  {
    name: "Mauritanian Ouguiya",
    code: "MRO",
    symbol: "UM",
    country: "MR",
  },
  {
    name: "Mauritian Rupee",
    code: "MUR",
    symbol: "₨",
    country: "MU",
  },
  {
    name: "Maldivian Rufiyaa",
    code: "MVR",
    symbol: "Rf",
    country: "MV",
  },
  {
    name: "Malawian Kwacha",
    code: "MWK",
    symbol: "MK",
    country: "MW",
  },
  {
    name: "Mexican Peso",
    code: "MXN",
    symbol: "$",
    country: "MX",
  },
  {
    name: "Malaysian Ringgit",
    code: "MYR",
    symbol: "RM",
    country: "MY",
  },
  {
    name: "Mozambican Metical",
    code: "MZN",
    symbol: "MT",
    country: "MZ",
  },
  {
    name: "Namibian Dollar",
    code: "NAD",
    symbol: "$",
    country: "NA",
  },
  {
    name: "Nigerian Naira",
    code: "NGN",
    symbol: "₦",
    country: "NG",
  },
  {
    name: "Nicaraguan Córdoba",
    code: "NIO",
    symbol: "C$",
    country: "NI",
  },
  {
    name: "Norwegian Krone",
    code: "NOK",
    symbol: "kr",
    country: "BV",
  },
  {
    name: "Nepalese Rupee",
    code: "NPR",
    symbol: "₨",
    country: "NP",
  },
  {
    name: "New Zealand Dollar",
    code: "NZD",
    symbol: "$",
    country: "CK",
  },
  {
    name: "Omani Rial",
    code: "OMR",
    symbol: "ر.ع.",
    country: "OM",
  },
  {
    name: "Panamanian Balboa",
    code: "PAB",
    symbol: "B/.",
    country: "PA",
  },
  {
    name: "Peruvian Sol",
    code: "PEN",
    symbol: "S/.",
    country: "PE",
  },
  {
    name: "Papua New Guinean Kina",
    code: "PGK",
    symbol: "K",
    country: "PG",
  },
  {
    name: "Philippine Peso",
    code: "PHP",
    symbol: "₱",
    country: "PH",
  },
  {
    name: "Pakistani Rupee",
    code: "PKR",
    symbol: "₨",
    country: "PK",
  },
  {
    name: "Polish Złoty",
    code: "PLN",
    symbol: "zł",
    country: "PL",
  },
  {
    name: "Paraguayan Guarani",
    code: "PYG",
    symbol: "₲",
    country: "PY",
  },
  {
    name: "Qatari Riyal",
    code: "QAR",
    symbol: "ر.ق",
    country: "QA",
  },
  {
    name: "Romanian Leu",
    code: "RON",
    symbol: "lei",
    country: "RO",
  },
  {
    name: "Serbian Dinar",
    code: "RSD",
    symbol: "дин.",
    country: "RS",
  },
  {
    name: "Russian Ruble",
    code: "RUB",
    symbol: "₽",
    country: "RU",
  },
  {
    name: "Rwandan Franc",
    code: "RWF",
    symbol: "FRw",
    country: "RW",
  },
  {
    name: "Saudi Riyal",
    code: "SAR",
    symbol: "ر.س",
    country: "SA",
  },
  {
    name: "Solomon Islands Dollar",
    code: "SBD",
    symbol: "$",
    country: "SB",
  },
  {
    name: "Seychellois Rupee",
    code: "SCR",
    symbol: "₨",
    country: "SC",
  },
  {
    name: "Sudanese Pound",
    code: "SDG",
    symbol: "ج.س.",
    country: "SD",
  },
  {
    name: "Swedish Krona",
    code: "SEK",
    symbol: "kr",
    country: "SE",
  },
  {
    name: "Singapore Dollar",
    code: "SGD",
    symbol: "$",
    country: "SG",
  },
  {
    name: "Saint Helena Pound",
    code: "SHP",
    symbol: "£",
    country: "SH",
  },
  {
    name: "Sierra Leonean Leone",
    code: "SLL",
    symbol: "Le",
    country: "SL",
  },
  {
    name: "Somali Shilling",
    code: "SOS",
    symbol: "Sh",
    country: "SO",
  },
  {
    name: "Surinamese Dollar",
    code: "SRD",
    symbol: "$",
    country: "SR",
  },
  {
    name: "South Sudanese Pound",
    code: "SSP",
    symbol: "£",
    country: "SS",
  },
  {
    name: "São Tomé and Príncipe Dobra",
    code: "STN",
    symbol: "Db",
    country: "ST",
  },
  {
    name: "Salvadoran Colón",
    code: "SVC",
    symbol: "$",
    country: "SV",
  },
  {
    name: "Syrian Pound",
    code: "SYP",
    symbol: "£",
    country: "SY",
  },
  {
    name: "Swazi Lilangeni",
    code: "SZL",
    symbol: "L",
    country: "SZ",
  },
  {
    name: "Thai Baht",
    code: "THB",
    symbol: "฿",
    country: "TH",
  },
  {
    name: "Tajikistani Somoni",
    code: "TJS",
    symbol: "SM",
    country: "TJ",
  },
  {
    name: "Turkmenistan Manat",
    code: "TMT",
    symbol: "m",
    country: "TM",
  },
  {
    name: "Tunisian Dinar",
    code: "TND",
    symbol: "د.ت",
    country: "TN",
  },
  {
    name: "Tongan Paʻanga",
    code: "TOP",
    symbol: "T$",
    country: "TO",
  },
  {
    name: "Turkish Lira",
    code: "TRY",
    symbol: "₺",
    country: "TR",
  },
  {
    name: "Trinidad and Tobago Dollar",
    code: "TTD",
    symbol: "TT$",
    country: "TT",
  },
  {
    name: "New Taiwan Dollar",
    code: "TWD",
    symbol: "NT$",
    country: "TW",
  },
  {
    name: "Tanzanian Shilling",
    code: "TZS",
    symbol: "Sh",
    country: "TZ",
  },
  {
    name: "Ukrainian Hryvnia",
    code: "UAH",
    symbol: "₴",
    country: "UA",
  },
  {
    name: "Ugandan Shilling",
    code: "UGX",
    symbol: "USh",
    country: "UG",
  },
  {
    name: "United States Dollar",
    code: "USD",
    symbol: "$",
    country: "AS",
  },
  {
    name: "Uruguayan Peso",
    code: "UYU",
    symbol: "$",
    country: "UY",
  },
  {
    name: "Uzbekistani So'm",
    code: "UZS",
    symbol: "лв",
    country: "UZ",
  },
  {
    name: "Venezuelan Bolívar",
    code: "VES",
    symbol: "Bs",
    country: "VE",
  },
  {
    name: "Vietnamese Đồng",
    code: "VND",
    symbol: "₫",
    country: "VN",
  },
  {
    name: "Vanuatu Vatu",
    code: "VUV",
    symbol: "VT",
    country: "VU",
  },
  {
    name: "Samoan Tala",
    code: "WST",
    symbol: "T",
    country: "WS",
  },
  {
    name: "Central African CFA Franc",
    code: "XAF",
    symbol: "FCFA",
    country: "CF",
  },
  {
    name: "East Caribbean Dollar",
    code: "XCD",
    symbol: "$",
    country: "AI",
  },
  {
    name: "West African CFA Franc",
    code: "XOF",
    symbol: "CFA",
    country: "BJ",
  },
  {
    name: "CFP Franc",
    code: "XPF",
    symbol: "₣",
    country: "PF",
  },
  {
    name: "Yemeni Rial",
    code: "YER",
    symbol: "﷼",
    country: "YE",
  },
  {
    name: "South African Rand",
    code: "ZAR",
    symbol: "R",
    country: "ZA",
  },
  {
    name: "Zambian Kwacha",
    code: "ZMW",
    symbol: "ZK",
    country: "ZM",
  },
  {
    name: "Zimbabwean Dollar",
    code: "ZWL",
    symbol: "$",
    country: "ZW",
  },
];
export default ALLCURRENCIES;
