export const OCCUPATIONS = [
  {
    id: 1,
    label: "Server (Waiter/Waitress)",
    value: "Server (Waiter/Waitress)",
  },
  { id: 2, label: "Housekeeping", value: "Housekeeping" },
  { id: 3, label: "Room Service Server", value: "Room Service Server" },
  { id: 4, label: "Baggage Porter", value: "Baggage Porter" },
  { id: 5, label: "Concierge", value: "Concierge" },
  { id: 6, label: "Tour Guide", value: "Tour Guide" },
  { id: 7, label: "Caddie", value: "Caddie" },
  { id: 8, label: "Banquet Server", value: "Banquet Server" },
  { id: 9, label: "Doorman/Door Woman", value: "Doorman/Door Woman" },
  { id: 10, label: "Valet", value: "Valet" },
  {
    id: 11,
    label: "Fitness Instructor/Personal Trainer",
    value: "Fitness Instructor/Personal Trainer",
  },
  { id: 12, label: "Yachtie", value: "Yachtie" },
  { id: 13, label: "House Cleaner", value: "House Cleaner" },
  { id: 14, label: "Busser", value: "Busser" },
  { id: 15, label: "Dog Walker", value: "Dog Walker" },
  { id: 16, label: "Pet Groomer", value: "Pet Groomer" },
  { id: 17, label: "Bartender", value: "Bartender" },
  { id: 18, label: "Musician", value: "Musician" },
  { id: 19, label: "Babysitter/Nanny", value: "Babysitter/Nanny" },
  { id: 20, label: "Hairstylist", value: "Hairstylist" },
  { id: 21, label: "Sommelier", value: "Sommelier" },
  { id: 22, label: "Driver/Chauffer", value: "Driver/Chauffer" },
  { id: 23, label: "Tattoo Artist", value: "Tattoo Artist" },
  { id: 24, label: "Landscaper", value: "Landscaper" },
  { id: 25, label: "Delivery Driver", value: "Delivery Driver" },
  { id: 26, label: "Butler", value: "Butler" },
  { id: 27, label: "Casino Dealer", value: "Casino Dealer" },
  { id: 28, label: "Massage Therapist", value: "Massage Therapist" },
  {
    id: 29,
    label: "Cosmetologist/Beauty Therapist",
    value: "Cosmetologist/Beauty Therapist",
  },
  {
    id: 30,
    label: "Cruise Ship Entertainer",
    value: "Cruise Ship Entertainer",
  },
  { id: 31, label: "Life Coach", value: "Life Coach" },
  { id: 32, label: "Music DJ", value: "Music DJ" },
  { id: 33, label: "Street Vendor", value: "Street Vendor" },
  { id: 34, label: "Dry Cleaner", value: "Dry Cleaner" },
  { id: 35, label: "Maintenance Engineer", value: "Maintenance Engineer" },
  { id: 36, label: "Fast Food Worker", value: "Fast Food Worker" },
  { id: 37, label: "Fine Dining Worker", value: "Fine Dining Worker" },
  { id: 38, label: "Contractor/Laborer", value: "Contractor/Laborer" },
  { id: 39, label: "Pool Technician", value: "Pool Technician" },
  { id: 40, label: "Aquarium Technician", value: "Aquarium Technician" },
  { id: 41, label: "Event Staff", value: "Event Staff" },
  { id: 42, label: "Security Staff", value: "Security Staff" },
  { id: 43, label: "Door Staff/Bouncer", value: "Door Staff/Bouncer" },
  { id: 44, label: "Sales Staff", value: "Sales Staff" },
  { id: 45, label: "Support Staff", value: "Support Staff" },
  {
    id: 46,
    label: "Other Services Provider",
    value: "Other Services Provider",
  },
  { id: 47, label: "Other Product Provider", value: "Other Product Provider" },
];
