export const SCREEN = {
  login: "login",
  register: "register",
  registerOptions: "registerOptions",
  otpVerification: "otpVerification",
  welcome: "welcome",
  drawer: "drawer",
  bottomTab: "bottom",
  home: "home",
  chat: "chat",
  notifications: "notifications",
  paymentOptions: "paymentOptions",
  scanQRCode: "scanQRCode",
  enterUniqueCode: "enterUniqueCode",
  calculateTipAmount: "calculateTipAmount",
  contactUs: "contactUs",
  savedCards: "savedCards",
  addCard: "Add Card",
  profile: "profile",
  scanCode: "scanCode",
  editProfile: "editProfile",
  chatScreen: "chatScreen",
  registerAsPayee: "registerAsPayee",
  teamMember: "teamMember",
  teamMemberProfile: "teamMemberProfile",
  recieveTips: "recieveTips",
  subscription: "subscription",
  splash: "splash",
  searchHistory: "searchHistory",
  forgotPasswordEmail: "forgotPasswordEmail",
  resetPassword: "resetPassword",
  webView: "webView",
  QR_Scanner: "Scanner",
  STRIPESCREEN: "StipeTermsScreen",
  businessDetails: "businessDetails",
  joinMultipleTeams: "joinMultipleTeams",
  myTeams: "myTeams",
};
